# SPDX-FileCopyrightText: © 2024 RepRep's DMP Template Authors <https://github.com/reproducible-reporting/dmp-template/blob/main/AUTHORS.md>
# SPDX-License-Identifier: CC-BY-NC-SA-4.0

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v6.0.0"
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: destroyed-symlinks
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.6
  hooks:
    - id: remove-crlf
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.7
  hooks:
    - id: ruff-format
    - id: ruff
      args: ["--fix", "--show-fixes"]
- repo: https://github.com/hukkin/mdformat
  rev: 1.0.0
  hooks:
  - id: mdformat
    additional_dependencies:
      - mdformat-gfm
      - mdformat-ruff
      - mdformat-config
- repo: https://github.com/fsfe/reuse-tool
  rev: v6.2.0
  hooks:
  - id: reuse
